project:
  type: book

book:
  title: "master-thesis-experiments"
  author: "Norah Jones"
  date: "11/10/2023"
  chapters:
    - index.qmd
    - chapters/ch01/intro.qmd
    - chapters/ch02/summary.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

