project:
  type: book
  #execute-dir: project

book:
  title: "master-thesis-experiments"
  author: 
    name: Kevin Hernández Rostrán
    orcid: 0009-0001-7682-0350
  url: https://kevinah95.github.io/master-thesis-experiments/
  repo-url: https://github.com/kevinah95/master-thesis-experiments/
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - chapters/ch01/install.qmd
    - chapters/ch02/architecture.qmd
    - chapters/ch03/experiments.qmd
    - chapters/references.qmd
  page-footer: "Build v1.5.0" # x-release-please-version

bibliography: references.bib

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    page-layout: full
    code-tools:
      source: true
      toggle: false
      caption: none
    code-fold: true
    code-summary: "Ver código"
    theme: cosmo
    css: styles/tabulator.css

freeze: true

editor: visual

