# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: preview

  preview:
    desc: Start a http server to serve the book.
    cmd: quarto preview

  preview:pdf:
    desc: Start a http server to serve the pdf book.
    cmd: quarto preview --to pdf

  render:pdf:
    desc: Render book as pdf.
    cmd: quarto render --to pdf

  clean:
    cmds:
      - rm -rf site_libs
      - rm -rf index_files
      - rm -rf output
